apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: software-templates
  annotations:
    github.com/project-slug: 'backstage/software-templates'
spec:
  type: service
  lifecycle: production
  owner: infinite-bucks
