apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: gitlab-merge-request
  title: GitLab Merge Request Action template
  description: Scaffolder template demo publishing a Merge Request on existing GitLab repository
spec:
  owner: backstage/techdocs-core
  type: service

  parameters:
    - title: Fill in some steps
      required:
        - name
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component
          ui:autofocus: true
          ui:options:
            rows: 5
        description:
          title: Description
          type: string
          description: Description of the component
        targetPath:
          title: Target Path in repo
          type: string
          description: Name of the directory to create in the repository
        branchName:
          title: Destination Branch Name
          type: string
          description: Name of the branch to create in the repository
        assignee:
          title: MR Assignee
          type: string
          description: GitLab Handle of the Assignee
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - gitlab.com
            requestUserCredentials:
              secretsKey: USER_OAUTH_TOKEN

  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        targetPath: ${{ parameters.targetPath }}
        values:
          name: ${{parameters.name}}
    - id: publish
      name: Publish
      action: publish:gitlab:merge-request
      input:
        repoUrl: ${{ parameters.repoUrl }}
        title: Creating catalog-info.yaml ${{ parameters.name }} for backstage
        branchName: ${{ parameters.branchName }}
        description: |
          # New project: ${{ parameters.name }}
          ${{ parameters.description if parameters.description }}
        targetPath: ${{ parameters.targetPath if parameters.targetPath else '.' }}
        token: ${{ secrets.USER_OAUTH_TOKEN }}
        commitAction: create
        removeSourceBranch: true
        assignee: ${{ parameters.assignee }}

  output:
    links: 
      - url: ${{ steps.publish.output.mergeRequestUrl }}
        title: 'Go to Gitlab MR'
